version: '3.4'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3030"
    depends_on:
      - appdb
      - pgadmin
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  appdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nestdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '8080:80'
    depends_on:
      - appdb
    networks:
      - app-network

volumes:
  db-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
